// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BusinessSummary
 */
export type BusinessSummary = {
    clients: number;
    expenses_ugx: number;
    invoice_outstanding_ugx: number;
    quotations_open: number;
    suppliers: number;
};

/**
 * ClientCreate
 */
export type ClientCreate = {
    address?: string | null;
    contact_person?: string | null;
    email?: string | null;
    name: string;
    notes?: string | null;
    phone?: string | null;
};

/**
 * ClientRead
 */
export type ClientRead = {
    address: string | null;
    contact_person: string | null;
    created_at: string;
    email: string | null;
    id: string;
    is_active: boolean;
    name: string;
    notes: string | null;
    phone: string | null;
    updated_at: string;
};

/**
 * DocumentCreate
 */
export type DocumentCreate = {
    category: string;
    content_type: string;
    extracted_fields?: {
        [key: string]: unknown;
    };
    ocr_status?: string;
    ocr_text?: string | null;
    original_filename: string;
    project_id?: string | null;
    size_bytes: number;
    storage_key: string;
    title: string;
};

/**
 * DocumentPresignRequest
 */
export type DocumentPresignRequest = {
    content_type: string;
    filename: string;
    project_id?: string | null;
};

/**
 * DocumentPresignResponse
 */
export type DocumentPresignResponse = {
    method?: string;
    storage_key: string;
    upload_url: string;
};

/**
 * DocumentRead
 */
export type DocumentRead = {
    category: string;
    content_type: string;
    created_at: string;
    extracted_fields: {
        [key: string]: unknown;
    };
    id: string;
    ocr_status: string;
    ocr_text: string | null;
    original_filename: string;
    project_id: string | null;
    size_bytes: number;
    storage_key: string;
    title: string;
    updated_at: string;
    uploaded_by_email: string;
};

/**
 * DocumentUpdate
 */
export type DocumentUpdate = {
    category?: string | null;
    extracted_fields?: {
        [key: string]: unknown;
    } | null;
    ocr_status?: string | null;
    ocr_text?: string | null;
    project_id?: string | null;
    title?: string | null;
};

/**
 * DownloadResponse
 */
export type DownloadResponse = {
    url: string;
};

/**
 * ExpenseCreate
 */
export type ExpenseCreate = {
    amount_ugx: number;
    category?: string;
    description: string;
    expense_date: string;
    project_id?: string | null;
    reference?: string | null;
    supplier_id?: string | null;
};

/**
 * ExpenseRead
 */
export type ExpenseRead = {
    amount_ugx: number;
    category: string;
    created_at: string;
    description: string;
    expense_date: string;
    id: string;
    project_id: string | null;
    reference: string | null;
    supplier_id: string | null;
    updated_at: string;
};

/**
 * InvoiceCreate
 */
export type InvoiceCreate = {
    amount_ugx: number;
    client_id?: string | null;
    client_name: string;
    due_date?: string | null;
    invoice_number: string;
    issue_date: string;
    notes?: string | null;
    paid_amount_ugx?: number;
    project_id?: string | null;
    status?: string;
};

/**
 * InvoiceRead
 */
export type InvoiceRead = {
    amount_ugx: number;
    client_id: string | null;
    client_name: string;
    created_at: string;
    due_date: string | null;
    id: string;
    invoice_number: string;
    issue_date: string;
    notes: string | null;
    paid_amount_ugx: number;
    project_id: string | null;
    status: string;
    updated_at: string;
};

/**
 * Message
 */
export type Message = {
    message: string;
};

/**
 * ProjectActivityItem
 */
export type ProjectActivityItem = {
    changed_by: string | null;
    created_at: string;
    id: string;
    operation: string;
    record_id: string;
    table_name: string;
    title: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    amount_paid_ugx?: number;
    client_name: string;
    description?: string | null;
    due_date?: string | null;
    name: string;
    progress?: number;
    project_manager_email?: string | null;
    start_date?: string | null;
    status?: string;
    value_ugx?: number;
};

/**
 * ProjectExpenseItem
 */
export type ProjectExpenseItem = {
    amount_ugx: number;
    category: string;
    description: string;
    expense_date: string;
    id: string;
    reference: string | null;
};

/**
 * ProjectFinanceRead
 */
export type ProjectFinanceRead = {
    amount_paid_ugx: number;
    expenses: Array<ProjectExpenseItem>;
    expenses_ugx: number;
    invoice_outstanding_ugx: number;
    invoice_paid_ugx: number;
    invoice_total_ugx: number;
    invoices: Array<ProjectInvoiceItem>;
    project_outstanding_ugx: number;
    project_value_ugx: number;
    purchase_orders: Array<ProjectPurchaseOrderItem>;
    purchase_orders_ugx: number;
    quotation_total_ugx: number;
    quotations: Array<ProjectQuotationItem>;
};

/**
 * ProjectInvoiceItem
 */
export type ProjectInvoiceItem = {
    amount_ugx: number;
    due_date: string | null;
    id: string;
    invoice_number: string;
    issue_date: string;
    paid_amount_ugx: number;
    status: string;
};

/**
 * ProjectPurchaseOrderItem
 */
export type ProjectPurchaseOrderItem = {
    amount_ugx: number;
    id: string;
    order_date: string;
    po_number: string;
    status: string;
    supplier_name: string;
};

/**
 * ProjectQuotationItem
 */
export type ProjectQuotationItem = {
    amount_ugx: number;
    id: string;
    issue_date: string;
    quotation_number: string;
    status: string;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    amount_paid_ugx: number;
    client_name: string;
    created_at: string;
    created_by_email: string;
    description: string | null;
    due_date: string | null;
    id: string;
    is_archived: boolean;
    name: string;
    progress: number;
    project_manager_email: string | null;
    start_date: string | null;
    status: string;
    updated_at: string;
    value_ugx: number;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    amount_paid_ugx?: number | null;
    client_name?: string | null;
    description?: string | null;
    due_date?: string | null;
    is_archived?: boolean | null;
    name?: string | null;
    progress?: number | null;
    project_manager_email?: string | null;
    start_date?: string | null;
    status?: string | null;
    value_ugx?: number | null;
};

/**
 * ProjectWorkspaceRead
 */
export type ProjectWorkspaceRead = {
    activity: Array<ProjectActivityItem>;
    documents: Array<DocumentRead>;
    finance: ProjectFinanceRead;
    project: ProjectRead;
    tasks: Array<TaskRead>;
};

/**
 * PurchaseOrderCreate
 */
export type PurchaseOrderCreate = {
    amount_ugx: number;
    expected_date?: string | null;
    notes?: string | null;
    order_date: string;
    po_number: string;
    project_id?: string | null;
    status?: string;
    supplier_id?: string | null;
    supplier_name: string;
};

/**
 * PurchaseOrderRead
 */
export type PurchaseOrderRead = {
    amount_ugx: number;
    created_at: string;
    expected_date: string | null;
    id: string;
    notes: string | null;
    order_date: string;
    po_number: string;
    project_id: string | null;
    status: string;
    supplier_id: string | null;
    supplier_name: string;
    updated_at: string;
};

/**
 * QuotationCreate
 */
export type QuotationCreate = {
    amount_ugx: number;
    client_id?: string | null;
    client_name: string;
    issue_date: string;
    notes?: string | null;
    project_id?: string | null;
    quotation_number: string;
    status?: string;
    valid_until?: string | null;
};

/**
 * QuotationRead
 */
export type QuotationRead = {
    amount_ugx: number;
    client_id: string | null;
    client_name: string;
    created_at: string;
    id: string;
    issue_date: string;
    notes: string | null;
    project_id: string | null;
    quotation_number: string;
    status: string;
    updated_at: string;
    valid_until: string | null;
};

/**
 * SupplierCreate
 */
export type SupplierCreate = {
    address?: string | null;
    contact_person?: string | null;
    email?: string | null;
    name: string;
    notes?: string | null;
    phone?: string | null;
};

/**
 * SupplierRead
 */
export type SupplierRead = {
    address: string | null;
    contact_person: string | null;
    created_at: string;
    email: string | null;
    id: string;
    is_active: boolean;
    name: string;
    notes: string | null;
    phone: string | null;
    updated_at: string;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    assignee_email?: string | null;
    description?: string | null;
    due_date?: string | null;
    priority?: string;
    project_id: string;
    status?: string;
    title: string;
};

/**
 * TaskRead
 */
export type TaskRead = {
    assignee_email: string | null;
    completed_at: string | null;
    created_at: string;
    description: string | null;
    due_date: string | null;
    id: string;
    priority: string;
    project_id: string;
    status: string;
    title: string;
    updated_at: string;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    assignee_email?: string | null;
    description?: string | null;
    due_date?: string | null;
    priority?: string | null;
    status?: string | null;
    title?: string | null;
};

/**
 * TelemetryRecord
 */
export type TelemetryRecord = {
    current_a: number;
    frequency_hz: number;
    power_factor: number;
    timestamp_epoch: number;
    transformer_id: string;
    voltage_v: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    access_token: string;
    expires_in?: number;
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * UserAdminCreate
 */
export type UserAdminCreate = {
    email: string;
    full_name: string;
    is_active?: boolean;
    is_superuser?: boolean;
    password: string;
};

/**
 * UserAdminUpdate
 */
export type UserAdminUpdate = {
    email?: string | null;
    full_name?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    password?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    email: string;
    full_name: string;
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    email: string;
    full_name: string;
    id: string;
    is_active: boolean;
    is_superuser: boolean;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    email?: string | null;
    full_name?: string | null;
    password?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    count: number;
    data: Array<UserRead>;
};

/**
 * WorkspaceSummary
 */
export type WorkspaceSummary = {
    active_projects: number;
    documents: number;
    due_tasks: number;
    outstanding_ugx: number;
    pending_tasks: number;
};

export type ApiV1AuthLoginLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type ApiV1AuthLoginLoginResponses = {
    /**
     * Document created, URL follows
     */
    201: TokenResponse;
};

export type ApiV1AuthLoginLoginResponse = ApiV1AuthLoginLoginResponses[keyof ApiV1AuthLoginLoginResponses];

export type ApiV1AuthLogoutLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type ApiV1AuthLogoutLogoutResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type ApiV1AuthLogoutLogoutResponse = ApiV1AuthLogoutLogoutResponses[keyof ApiV1AuthLogoutLogoutResponses];

export type ApiV1AuthTokenTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token';
};

export type ApiV1AuthTokenTokenResponses = {
    /**
     * Document created, URL follows
     */
    201: TokenResponse;
};

export type ApiV1AuthTokenTokenResponse = ApiV1AuthTokenTokenResponses[keyof ApiV1AuthTokenTokenResponses];

export type ApiV1BusinessClientsClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/clients';
};

export type ApiV1BusinessClientsClientsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ClientRead>;
};

export type ApiV1BusinessClientsClientsResponse = ApiV1BusinessClientsClientsResponses[keyof ApiV1BusinessClientsClientsResponses];

export type ApiV1BusinessClientsCreateClientData = {
    body: ClientCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/clients';
};

export type ApiV1BusinessClientsCreateClientErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsCreateClientError = ApiV1BusinessClientsCreateClientErrors[keyof ApiV1BusinessClientsCreateClientErrors];

export type ApiV1BusinessClientsCreateClientResponses = {
    /**
     * Document created, URL follows
     */
    201: ClientRead;
};

export type ApiV1BusinessClientsCreateClientResponse = ApiV1BusinessClientsCreateClientResponses[keyof ApiV1BusinessClientsCreateClientResponses];

export type ApiV1BusinessExpensesExpensesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/expenses';
};

export type ApiV1BusinessExpensesExpensesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ExpenseRead>;
};

export type ApiV1BusinessExpensesExpensesResponse = ApiV1BusinessExpensesExpensesResponses[keyof ApiV1BusinessExpensesExpensesResponses];

export type ApiV1BusinessExpensesCreateExpenseData = {
    body: ExpenseCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/expenses';
};

export type ApiV1BusinessExpensesCreateExpenseErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessExpensesCreateExpenseError = ApiV1BusinessExpensesCreateExpenseErrors[keyof ApiV1BusinessExpensesCreateExpenseErrors];

export type ApiV1BusinessExpensesCreateExpenseResponses = {
    /**
     * Document created, URL follows
     */
    201: ExpenseRead;
};

export type ApiV1BusinessExpensesCreateExpenseResponse = ApiV1BusinessExpensesCreateExpenseResponses[keyof ApiV1BusinessExpensesCreateExpenseResponses];

export type ApiV1BusinessInvoicesInvoicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/invoices';
};

export type ApiV1BusinessInvoicesInvoicesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<InvoiceRead>;
};

export type ApiV1BusinessInvoicesInvoicesResponse = ApiV1BusinessInvoicesInvoicesResponses[keyof ApiV1BusinessInvoicesInvoicesResponses];

export type ApiV1BusinessInvoicesCreateInvoiceData = {
    body: InvoiceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/invoices';
};

export type ApiV1BusinessInvoicesCreateInvoiceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessInvoicesCreateInvoiceError = ApiV1BusinessInvoicesCreateInvoiceErrors[keyof ApiV1BusinessInvoicesCreateInvoiceErrors];

export type ApiV1BusinessInvoicesCreateInvoiceResponses = {
    /**
     * Document created, URL follows
     */
    201: InvoiceRead;
};

export type ApiV1BusinessInvoicesCreateInvoiceResponse = ApiV1BusinessInvoicesCreateInvoiceResponses[keyof ApiV1BusinessInvoicesCreateInvoiceResponses];

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/purchase-orders';
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PurchaseOrderRead>;
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersResponse = ApiV1BusinessPurchaseOrdersPurchaseOrdersResponses[keyof ApiV1BusinessPurchaseOrdersPurchaseOrdersResponses];

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderData = {
    body: PurchaseOrderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/purchase-orders';
};

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderError = ApiV1BusinessPurchaseOrdersCreatePurchaseOrderErrors[keyof ApiV1BusinessPurchaseOrdersCreatePurchaseOrderErrors];

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponses = {
    /**
     * Document created, URL follows
     */
    201: PurchaseOrderRead;
};

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponse = ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponses[keyof ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponses];

export type ApiV1BusinessQuotationsQuotationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/quotations';
};

export type ApiV1BusinessQuotationsQuotationsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<QuotationRead>;
};

export type ApiV1BusinessQuotationsQuotationsResponse = ApiV1BusinessQuotationsQuotationsResponses[keyof ApiV1BusinessQuotationsQuotationsResponses];

export type ApiV1BusinessQuotationsCreateQuotationData = {
    body: QuotationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/quotations';
};

export type ApiV1BusinessQuotationsCreateQuotationErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsCreateQuotationError = ApiV1BusinessQuotationsCreateQuotationErrors[keyof ApiV1BusinessQuotationsCreateQuotationErrors];

export type ApiV1BusinessQuotationsCreateQuotationResponses = {
    /**
     * Document created, URL follows
     */
    201: QuotationRead;
};

export type ApiV1BusinessQuotationsCreateQuotationResponse = ApiV1BusinessQuotationsCreateQuotationResponses[keyof ApiV1BusinessQuotationsCreateQuotationResponses];

export type ApiV1BusinessSummarySummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/summary';
};

export type ApiV1BusinessSummarySummaryResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: BusinessSummary;
};

export type ApiV1BusinessSummarySummaryResponse = ApiV1BusinessSummarySummaryResponses[keyof ApiV1BusinessSummarySummaryResponses];

export type ApiV1BusinessSuppliersSuppliersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/suppliers';
};

export type ApiV1BusinessSuppliersSuppliersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<SupplierRead>;
};

export type ApiV1BusinessSuppliersSuppliersResponse = ApiV1BusinessSuppliersSuppliersResponses[keyof ApiV1BusinessSuppliersSuppliersResponses];

export type ApiV1BusinessSuppliersCreateSupplierData = {
    body: SupplierCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/suppliers';
};

export type ApiV1BusinessSuppliersCreateSupplierErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersCreateSupplierError = ApiV1BusinessSuppliersCreateSupplierErrors[keyof ApiV1BusinessSuppliersCreateSupplierErrors];

export type ApiV1BusinessSuppliersCreateSupplierResponses = {
    /**
     * Document created, URL follows
     */
    201: SupplierRead;
};

export type ApiV1BusinessSuppliersCreateSupplierResponse = ApiV1BusinessSuppliersCreateSupplierResponses[keyof ApiV1BusinessSuppliersCreateSupplierResponses];

export type ApiV1DocumentsListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        project_id?: string | null;
        q?: string | null;
    };
    url: '/api/v1/documents';
};

export type ApiV1DocumentsListDocumentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsListDocumentsError = ApiV1DocumentsListDocumentsErrors[keyof ApiV1DocumentsListDocumentsErrors];

export type ApiV1DocumentsListDocumentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<DocumentRead>;
};

export type ApiV1DocumentsListDocumentsResponse = ApiV1DocumentsListDocumentsResponses[keyof ApiV1DocumentsListDocumentsResponses];

export type ApiV1DocumentsCreateDocumentData = {
    body: DocumentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/documents';
};

export type ApiV1DocumentsCreateDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsCreateDocumentError = ApiV1DocumentsCreateDocumentErrors[keyof ApiV1DocumentsCreateDocumentErrors];

export type ApiV1DocumentsCreateDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: DocumentRead;
};

export type ApiV1DocumentsCreateDocumentResponse = ApiV1DocumentsCreateDocumentResponses[keyof ApiV1DocumentsCreateDocumentResponses];

export type ApiV1DocumentsPresignCreateUploadUrlData = {
    body: DocumentPresignRequest;
    path?: never;
    query?: never;
    url: '/api/v1/documents/presign';
};

export type ApiV1DocumentsPresignCreateUploadUrlErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsPresignCreateUploadUrlError = ApiV1DocumentsPresignCreateUploadUrlErrors[keyof ApiV1DocumentsPresignCreateUploadUrlErrors];

export type ApiV1DocumentsPresignCreateUploadUrlResponses = {
    /**
     * Document created, URL follows
     */
    201: DocumentPresignResponse;
};

export type ApiV1DocumentsPresignCreateUploadUrlResponse = ApiV1DocumentsPresignCreateUploadUrlResponses[keyof ApiV1DocumentsPresignCreateUploadUrlResponses];

export type ApiV1DocumentsDocumentIdDeleteDocumentData = {
    body?: never;
    path: {
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type ApiV1DocumentsDocumentIdDeleteDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsDocumentIdDeleteDocumentError = ApiV1DocumentsDocumentIdDeleteDocumentErrors[keyof ApiV1DocumentsDocumentIdDeleteDocumentErrors];

export type ApiV1DocumentsDocumentIdDeleteDocumentResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiV1DocumentsDocumentIdDeleteDocumentResponse = ApiV1DocumentsDocumentIdDeleteDocumentResponses[keyof ApiV1DocumentsDocumentIdDeleteDocumentResponses];

export type ApiV1DocumentsDocumentIdUpdateDocumentData = {
    body: DocumentUpdate;
    path: {
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type ApiV1DocumentsDocumentIdUpdateDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsDocumentIdUpdateDocumentError = ApiV1DocumentsDocumentIdUpdateDocumentErrors[keyof ApiV1DocumentsDocumentIdUpdateDocumentErrors];

export type ApiV1DocumentsDocumentIdUpdateDocumentResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DocumentRead;
};

export type ApiV1DocumentsDocumentIdUpdateDocumentResponse = ApiV1DocumentsDocumentIdUpdateDocumentResponses[keyof ApiV1DocumentsDocumentIdUpdateDocumentResponses];

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlData = {
    body?: never;
    path: {
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/download';
};

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlError = ApiV1DocumentsDocumentIdDownloadGetDownloadUrlErrors[keyof ApiV1DocumentsDocumentIdDownloadGetDownloadUrlErrors];

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DownloadResponse;
};

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponse = ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponses[keyof ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponses];

export type ApiV1ProjectsListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string | null;
        include_archived?: boolean;
    };
    url: '/api/v1/projects';
};

export type ApiV1ProjectsListProjectsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsListProjectsError = ApiV1ProjectsListProjectsErrors[keyof ApiV1ProjectsListProjectsErrors];

export type ApiV1ProjectsListProjectsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ProjectRead>;
};

export type ApiV1ProjectsListProjectsResponse = ApiV1ProjectsListProjectsResponses[keyof ApiV1ProjectsListProjectsResponses];

export type ApiV1ProjectsCreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type ApiV1ProjectsCreateProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsCreateProjectError = ApiV1ProjectsCreateProjectErrors[keyof ApiV1ProjectsCreateProjectErrors];

export type ApiV1ProjectsCreateProjectResponses = {
    /**
     * Document created, URL follows
     */
    201: ProjectRead;
};

export type ApiV1ProjectsCreateProjectResponse = ApiV1ProjectsCreateProjectResponses[keyof ApiV1ProjectsCreateProjectResponses];

export type ApiV1ProjectsProjectIdArchiveProjectData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ApiV1ProjectsProjectIdArchiveProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdArchiveProjectError = ApiV1ProjectsProjectIdArchiveProjectErrors[keyof ApiV1ProjectsProjectIdArchiveProjectErrors];

export type ApiV1ProjectsProjectIdArchiveProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiV1ProjectsProjectIdArchiveProjectResponse = ApiV1ProjectsProjectIdArchiveProjectResponses[keyof ApiV1ProjectsProjectIdArchiveProjectResponses];

export type ApiV1ProjectsProjectIdGetProjectData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ApiV1ProjectsProjectIdGetProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdGetProjectError = ApiV1ProjectsProjectIdGetProjectErrors[keyof ApiV1ProjectsProjectIdGetProjectErrors];

export type ApiV1ProjectsProjectIdGetProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectRead;
};

export type ApiV1ProjectsProjectIdGetProjectResponse = ApiV1ProjectsProjectIdGetProjectResponses[keyof ApiV1ProjectsProjectIdGetProjectResponses];

export type ApiV1ProjectsProjectIdUpdateProjectData = {
    body: ProjectUpdate;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ApiV1ProjectsProjectIdUpdateProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdUpdateProjectError = ApiV1ProjectsProjectIdUpdateProjectErrors[keyof ApiV1ProjectsProjectIdUpdateProjectErrors];

export type ApiV1ProjectsProjectIdUpdateProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectRead;
};

export type ApiV1ProjectsProjectIdUpdateProjectResponse = ApiV1ProjectsProjectIdUpdateProjectResponses[keyof ApiV1ProjectsProjectIdUpdateProjectResponses];

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/workspace';
};

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceError = ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceErrors[keyof ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceErrors];

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectWorkspaceRead;
};

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponse = ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponses[keyof ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponses];

export type ApiV1TasksListTasksData = {
    body?: never;
    path?: never;
    query?: {
        project_id?: string | null;
        status?: string | null;
    };
    url: '/api/v1/tasks';
};

export type ApiV1TasksListTasksErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksListTasksError = ApiV1TasksListTasksErrors[keyof ApiV1TasksListTasksErrors];

export type ApiV1TasksListTasksResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<TaskRead>;
};

export type ApiV1TasksListTasksResponse = ApiV1TasksListTasksResponses[keyof ApiV1TasksListTasksResponses];

export type ApiV1TasksCreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tasks';
};

export type ApiV1TasksCreateTaskErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksCreateTaskError = ApiV1TasksCreateTaskErrors[keyof ApiV1TasksCreateTaskErrors];

export type ApiV1TasksCreateTaskResponses = {
    /**
     * Document created, URL follows
     */
    201: TaskRead;
};

export type ApiV1TasksCreateTaskResponse = ApiV1TasksCreateTaskResponses[keyof ApiV1TasksCreateTaskResponses];

export type ApiV1TasksTaskIdUpdateTaskData = {
    body: TaskUpdate;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type ApiV1TasksTaskIdUpdateTaskErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksTaskIdUpdateTaskError = ApiV1TasksTaskIdUpdateTaskErrors[keyof ApiV1TasksTaskIdUpdateTaskErrors];

export type ApiV1TasksTaskIdUpdateTaskResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TaskRead;
};

export type ApiV1TasksTaskIdUpdateTaskResponse = ApiV1TasksTaskIdUpdateTaskResponses[keyof ApiV1TasksTaskIdUpdateTaskResponses];

export type ApiV1TelemetryIngestIngestData = {
    body: Array<TelemetryRecord>;
    path?: never;
    query?: never;
    url: '/api/v1/telemetry/ingest';
};

export type ApiV1TelemetryIngestIngestErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TelemetryIngestIngestError = ApiV1TelemetryIngestIngestErrors[keyof ApiV1TelemetryIngestIngestErrors];

export type ApiV1TelemetryIngestIngestResponses = {
    /**
     * Request accepted, processing continues off-line
     */
    202: {
        [key: string]: unknown;
    };
};

export type ApiV1TelemetryIngestIngestResponse = ApiV1TelemetryIngestIngestResponses[keyof ApiV1TelemetryIngestIngestResponses];

export type ApiV1UsersListUsersData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/users';
};

export type ApiV1UsersListUsersErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersListUsersError = ApiV1UsersListUsersErrors[keyof ApiV1UsersListUsersErrors];

export type ApiV1UsersListUsersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UsersPublic;
};

export type ApiV1UsersListUsersResponse = ApiV1UsersListUsersResponses[keyof ApiV1UsersListUsersResponses];

export type ApiV1UsersCreateUserAdminData = {
    body: UserAdminCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type ApiV1UsersCreateUserAdminErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersCreateUserAdminError = ApiV1UsersCreateUserAdminErrors[keyof ApiV1UsersCreateUserAdminErrors];

export type ApiV1UsersCreateUserAdminResponses = {
    /**
     * Document created, URL follows
     */
    201: UserRead;
};

export type ApiV1UsersCreateUserAdminResponse = ApiV1UsersCreateUserAdminResponses[keyof ApiV1UsersCreateUserAdminResponses];

export type ApiV1UsersMeDeleteMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ApiV1UsersMeDeleteMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type ApiV1UsersMeDeleteMeResponse = ApiV1UsersMeDeleteMeResponses[keyof ApiV1UsersMeDeleteMeResponses];

export type ApiV1UsersMeGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ApiV1UsersMeGetMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersMeGetMeResponse = ApiV1UsersMeGetMeResponses[keyof ApiV1UsersMeGetMeResponses];

export type ApiV1UsersMeUpdateMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ApiV1UsersMeUpdateMeErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersMeUpdateMeError = ApiV1UsersMeUpdateMeErrors[keyof ApiV1UsersMeUpdateMeErrors];

export type ApiV1UsersMeUpdateMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersMeUpdateMeResponse = ApiV1UsersMeUpdateMeResponses[keyof ApiV1UsersMeUpdateMeResponses];

export type ApiV1UsersMePasswordUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type ApiV1UsersMePasswordUpdatePasswordMeErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersMePasswordUpdatePasswordMeError = ApiV1UsersMePasswordUpdatePasswordMeErrors[keyof ApiV1UsersMePasswordUpdatePasswordMeErrors];

export type ApiV1UsersMePasswordUpdatePasswordMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type ApiV1UsersMePasswordUpdatePasswordMeResponse = ApiV1UsersMePasswordUpdatePasswordMeResponses[keyof ApiV1UsersMePasswordUpdatePasswordMeResponses];

export type ApiV1UsersRegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/register';
};

export type ApiV1UsersRegisterRegisterErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersRegisterRegisterError = ApiV1UsersRegisterRegisterErrors[keyof ApiV1UsersRegisterRegisterErrors];

export type ApiV1UsersRegisterRegisterResponses = {
    /**
     * Document created, URL follows
     */
    201: UserRead;
};

export type ApiV1UsersRegisterRegisterResponse = ApiV1UsersRegisterRegisterResponses[keyof ApiV1UsersRegisterRegisterResponses];

export type ApiV1UsersSignupSignupData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type ApiV1UsersSignupSignupErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersSignupSignupError = ApiV1UsersSignupSignupErrors[keyof ApiV1UsersSignupSignupErrors];

export type ApiV1UsersSignupSignupResponses = {
    /**
     * Document created, URL follows
     */
    201: UserRead;
};

export type ApiV1UsersSignupSignupResponse = ApiV1UsersSignupSignupResponses[keyof ApiV1UsersSignupSignupResponses];

export type ApiV1UsersUserIdDeleteUserData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ApiV1UsersUserIdDeleteUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdDeleteUserError = ApiV1UsersUserIdDeleteUserErrors[keyof ApiV1UsersUserIdDeleteUserErrors];

export type ApiV1UsersUserIdDeleteUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type ApiV1UsersUserIdDeleteUserResponse = ApiV1UsersUserIdDeleteUserResponses[keyof ApiV1UsersUserIdDeleteUserResponses];

export type ApiV1UsersUserIdGetUserByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ApiV1UsersUserIdGetUserByIdErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdGetUserByIdError = ApiV1UsersUserIdGetUserByIdErrors[keyof ApiV1UsersUserIdGetUserByIdErrors];

export type ApiV1UsersUserIdGetUserByIdResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersUserIdGetUserByIdResponse = ApiV1UsersUserIdGetUserByIdResponses[keyof ApiV1UsersUserIdGetUserByIdResponses];

export type ApiV1UsersUserIdUpdateUserAdminData = {
    body: UserAdminUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ApiV1UsersUserIdUpdateUserAdminErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdUpdateUserAdminError = ApiV1UsersUserIdUpdateUserAdminErrors[keyof ApiV1UsersUserIdUpdateUserAdminErrors];

export type ApiV1UsersUserIdUpdateUserAdminResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersUserIdUpdateUserAdminResponse = ApiV1UsersUserIdUpdateUserAdminResponses[keyof ApiV1UsersUserIdUpdateUserAdminResponses];

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminData = {
    body: UserAdminUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/role';
};

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminError = ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors[keyof ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors];

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminResponse = ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses[keyof ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses];

export type ApiV1UtilsHealthCheckHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check';
};

export type ApiV1UtilsHealthCheckHealthCheckResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: boolean;
};

export type ApiV1UtilsHealthCheckHealthCheckResponse = ApiV1UtilsHealthCheckHealthCheckResponses[keyof ApiV1UtilsHealthCheckHealthCheckResponses];

export type ApiV1UtilsTestEmailTestEmailData = {
    body: {
        [key: string]: unknown;
    } | null;
    path?: never;
    query?: {
        email_to?: string | null;
    };
    url: '/api/v1/utils/test-email';
};

export type ApiV1UtilsTestEmailTestEmailErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UtilsTestEmailTestEmailError = ApiV1UtilsTestEmailTestEmailErrors[keyof ApiV1UtilsTestEmailTestEmailErrors];

export type ApiV1UtilsTestEmailTestEmailResponses = {
    /**
     * Document created, URL follows
     */
    201: Message;
};

export type ApiV1UtilsTestEmailTestEmailResponse = ApiV1UtilsTestEmailTestEmailResponses[keyof ApiV1UtilsTestEmailTestEmailResponses];

export type ApiV1WorkspaceSummarySummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workspace/summary';
};

export type ApiV1WorkspaceSummarySummaryResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: WorkspaceSummary;
};

export type ApiV1WorkspaceSummarySummaryResponse = ApiV1WorkspaceSummarySummaryResponses[keyof ApiV1WorkspaceSummarySummaryResponses];

export type HealthGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthGetHealthResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type HealthGetHealthResponse = HealthGetHealthResponses[keyof HealthGetHealthResponses];

export type HealthLiveGetLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveGetLivenessResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type HealthLiveGetLivenessResponse = HealthLiveGetLivenessResponses[keyof HealthLiveGetLivenessResponses];

export type HealthReadyGetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyGetReadinessResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthReadyGetReadinessResponse = HealthReadyGetReadinessResponses[keyof HealthReadyGetReadinessResponses];

export type HealthStartupGetStartupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/startup';
};

export type HealthStartupGetStartupResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthStartupGetStartupResponse = HealthStartupGetStartupResponses[keyof HealthStartupGetStartupResponses];

export type MetricsMetricsEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type MetricsMetricsEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type MetricsMetricsEndpointResponse = MetricsMetricsEndpointResponses[keyof MetricsMetricsEndpointResponses];
