// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActivityItem
 */
export type ActivityItem = {
    detail: string | null;
    kind: string;
    label: string;
    occurred_at: string;
    record_id: string;
};

/**
 * BusinessSummary
 */
export type BusinessSummary = {
    active_clients: number;
    active_suppliers: number;
    clients: number;
    expenses_month_ugx: number;
    expenses_ugx: number;
    invoice_outstanding_ugx: number;
    outstanding_invoices: number;
    purchase_orders_open: number;
    quotations_open: number;
    receipts_month_ugx: number;
    receivables_ugx: number;
    suppliers: number;
    total_clients: number;
    total_suppliers: number;
};

/**
 * ClientCreate
 */
export type ClientCreate = {
    address?: string | null;
    contact_person?: string | null;
    email?: string | null;
    name: string;
    notes?: string | null;
    phone?: string | null;
};

/**
 * ClientRead
 */
export type ClientRead = {
    address: string | null;
    contact_person: string | null;
    created_at: string;
    email: string | null;
    id: string;
    is_active: boolean;
    name: string;
    notes: string | null;
    phone: string | null;
    updated_at: string;
};

/**
 * ClientStatementSummary
 */
export type ClientStatementSummary = {
    client_id: string;
    client_name: string;
    invoiced_ugx: number;
    outstanding_ugx: number;
    paid_ugx: number;
};

/**
 * ClientUpdate
 */
export type ClientUpdate = {
    address?: string | null;
    contact_person?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    name?: string | null;
    notes?: string | null;
    phone?: string | null;
};

/**
 * ClientWorkspace
 */
export type ClientWorkspace = {
    activity: Array<ActivityItem>;
    client: ClientRead;
    documents: Array<PartyDocumentItem>;
    invoices: Array<InvoiceRead>;
    outstanding_balance_ugx: number;
    projects: Array<PartyProjectItem>;
    quotations: Array<QuotationRead>;
    receipts: Array<ReceiptRead>;
};

/**
 * CommercialDocumentRead
 */
export type CommercialDocumentRead = {
    document_id: string | null;
    document_number: string;
    download_url: string | null;
    filename: string;
    stored: boolean;
};

/**
 * CommercialLineItemInput
 */
export type CommercialLineItemInput = {
    description: string;
    quantity?: number;
    unit_price_ugx?: number;
};

/**
 * CommercialLineItemRead
 */
export type CommercialLineItemRead = {
    amount_ugx: number;
    description: string;
    id: string;
    position: number;
    quantity: number;
    unit_price_ugx: number;
};

/**
 * DocumentCreate
 */
export type DocumentCreate = {
    category: string;
    client_id?: string | null;
    content_type: string;
    extracted_fields?: {
        [key: string]: unknown;
    };
    ocr_status?: string;
    ocr_text?: string | null;
    original_filename: string;
    project_id?: string | null;
    related_record_id?: string | null;
    related_record_type?: string | null;
    review_status?: string;
    size_bytes: number;
    storage_key: string;
    supplier_id?: string | null;
    title: string;
};

/**
 * DocumentPresignRequest
 */
export type DocumentPresignRequest = {
    content_type: string;
    filename: string;
    project_id?: string | null;
};

/**
 * DocumentPresignResponse
 */
export type DocumentPresignResponse = {
    method?: string;
    storage_key: string;
    upload_url: string;
};

/**
 * DocumentRead
 */
export type DocumentRead = {
    category: string;
    client_id: string | null;
    content_type: string;
    created_at: string;
    extracted_fields: {
        [key: string]: unknown;
    };
    id: string;
    ocr_status: string;
    ocr_text: string | null;
    original_filename: string;
    project_id: string | null;
    related_record_id: string | null;
    related_record_type: string | null;
    review_status: string;
    size_bytes: number;
    storage_key: string;
    supplier_id: string | null;
    title: string;
    updated_at: string;
    uploaded_by_email: string;
};

/**
 * DocumentUpdate
 */
export type DocumentUpdate = {
    category?: string | null;
    client_id?: string | null;
    extracted_fields?: {
        [key: string]: unknown;
    } | null;
    ocr_status?: string | null;
    ocr_text?: string | null;
    project_id?: string | null;
    related_record_id?: string | null;
    related_record_type?: string | null;
    review_status?: string | null;
    supplier_id?: string | null;
    title?: string | null;
};

/**
 * DownloadResponse
 */
export type DownloadResponse = {
    url: string;
};

/**
 * ExpenseCreate
 */
export type ExpenseCreate = {
    amount_ugx: number;
    category?: string;
    description: string;
    expense_date: string;
    project_id?: string | null;
    reference?: string | null;
    supplier_id?: string | null;
    supporting_document_id?: string | null;
};

/**
 * ExpenseRead
 */
export type ExpenseRead = {
    amount_ugx: number;
    category: string;
    created_at: string;
    description: string;
    expense_date: string;
    id: string;
    project_id: string | null;
    reference: string | null;
    supplier_id: string | null;
    supporting_document_id: string | null;
    updated_at: string;
};

/**
 * InvoiceCreate
 */
export type InvoiceCreate = {
    amount_ugx: number;
    client_id?: string | null;
    client_name: string;
    due_date?: string | null;
    invoice_number: string;
    issue_date: string;
    items?: Array<CommercialLineItemInput>;
    notes?: string | null;
    paid_amount_ugx?: number;
    project_id?: string | null;
    status?: string;
};

/**
 * InvoiceRead
 */
export type InvoiceRead = {
    amount_ugx: number;
    client_id: string | null;
    client_name: string;
    created_at: string;
    due_date: string | null;
    id: string;
    invoice_number: string;
    issue_date: string;
    items?: Array<CommercialLineItemRead>;
    notes: string | null;
    outstanding_amount_ugx: number;
    paid_amount_ugx: number;
    project_id: string | null;
    source_quotation_id?: string | null;
    status: string;
    updated_at: string;
};

/**
 * InvoiceUpdate
 */
export type InvoiceUpdate = {
    amount_ugx?: number | null;
    client_id?: string | null;
    client_name?: string | null;
    due_date?: string | null;
    issue_date?: string | null;
    items?: Array<CommercialLineItemInput>;
    notes?: string | null;
    project_id?: string | null;
    status?: string | null;
};

/**
 * Message
 */
export type Message = {
    message: string;
};

/**
 * PartyDocumentItem
 */
export type PartyDocumentItem = {
    category: string;
    created_at: string;
    id: string;
    original_filename: string;
    project_id: string | null;
    title: string;
};

/**
 * PartyProjectItem
 */
export type PartyProjectItem = {
    amount_paid_ugx: number;
    due_date: string | null;
    id: string;
    name: string;
    progress: number;
    status: string;
    value_ugx: number;
};

/**
 * PaymentCreate
 */
export type PaymentCreate = {
    amount_ugx: number;
    client_id?: string | null;
    invoice_id?: string | null;
    method?: string;
    notes?: string | null;
    payment_date: string;
    project_id?: string | null;
    reference?: string | null;
};

/**
 * PaymentRead
 */
export type PaymentRead = {
    amount_ugx: number;
    client_id: string | null;
    created_at: string;
    id: string;
    invoice_id: string | null;
    method: string;
    notes: string | null;
    payment_date: string;
    project_id: string | null;
    receipt_number: string | null;
    recorded_by_email: string;
    reference: string | null;
    updated_at: string;
};

/**
 * ProjectActivityItem
 */
export type ProjectActivityItem = {
    changed_by: string | null;
    created_at: string;
    id: string;
    operation: string;
    record_id: string;
    summary: string;
    table_name: string;
    title: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    amount_paid_ugx?: number;
    client_id?: string | null;
    client_name: string;
    current_milestone?: string | null;
    description?: string | null;
    due_date?: string | null;
    name: string;
    progress?: number;
    project_manager_email?: string | null;
    start_date?: string | null;
    status?: string;
    tags?: Array<string>;
    team_emails?: Array<string>;
    value_ugx?: number;
};

/**
 * ProjectDashboardSummary
 */
export type ProjectDashboardSummary = {
    active_projects: number;
    amount_received_ugx: number;
    completed_projects: number;
    outstanding_ugx: number;
    overdue_projects: number;
    planning_projects: number;
    projects_needing_attention: number;
    tasks_due: number;
    total_project_value_ugx: number;
    total_projects: number;
};

/**
 * ProjectExpenseItem
 */
export type ProjectExpenseItem = {
    amount_ugx: number;
    category: string;
    description: string;
    expense_date: string;
    id: string;
    reference: string | null;
};

/**
 * ProjectFinanceRead
 */
export type ProjectFinanceRead = {
    amount_paid_ugx: number;
    expenses: Array<ProjectExpenseItem>;
    expenses_ugx: number;
    invoice_outstanding_ugx: number;
    invoice_paid_ugx: number;
    invoice_total_ugx: number;
    invoices: Array<ProjectInvoiceItem>;
    payment_total_ugx: number;
    payments: Array<ProjectPaymentItem>;
    project_outstanding_ugx: number;
    project_value_ugx: number;
    purchase_orders: Array<ProjectPurchaseOrderItem>;
    purchase_orders_ugx: number;
    quotation_total_ugx: number;
    quotations: Array<ProjectQuotationItem>;
};

/**
 * ProjectInvoiceItem
 */
export type ProjectInvoiceItem = {
    amount_ugx: number;
    due_date: string | null;
    id: string;
    invoice_number: string;
    issue_date: string;
    paid_amount_ugx: number;
    status: string;
};

/**
 * ProjectPaymentItem
 */
export type ProjectPaymentItem = {
    amount_ugx: number;
    id: string;
    invoice_id: string | null;
    method: string;
    notes: string | null;
    payment_date: string;
    reference: string | null;
};

/**
 * ProjectPurchaseOrderItem
 */
export type ProjectPurchaseOrderItem = {
    amount_ugx: number;
    id: string;
    order_date: string;
    po_number: string;
    status: string;
    supplier_name: string;
};

/**
 * ProjectQuotationItem
 */
export type ProjectQuotationItem = {
    amount_ugx: number;
    id: string;
    issue_date: string;
    quotation_number: string;
    status: string;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    amount_paid_ugx: number;
    client_id: string | null;
    client_name: string;
    created_at: string;
    created_by_email: string;
    current_milestone: string | null;
    description: string | null;
    due_date: string | null;
    id: string;
    is_archived: boolean;
    name: string;
    progress: number;
    project_manager_email: string | null;
    start_date: string | null;
    status: string;
    tags: Array<string>;
    team_emails: Array<string>;
    updated_at: string;
    value_ugx: number;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    amount_paid_ugx?: number | null;
    client_id?: string | null;
    client_name?: string | null;
    current_milestone?: string | null;
    description?: string | null;
    due_date?: string | null;
    is_archived?: boolean | null;
    name?: string | null;
    progress?: number | null;
    project_manager_email?: string | null;
    start_date?: string | null;
    status?: string | null;
    tags?: Array<string> | null;
    team_emails?: Array<string> | null;
    value_ugx?: number | null;
};

/**
 * ProjectWorkspaceRead
 */
export type ProjectWorkspaceRead = {
    activity: Array<ProjectActivityItem>;
    documents: Array<DocumentRead>;
    finance: ProjectFinanceRead;
    project: ProjectRead;
    tasks: Array<TaskRead>;
};

/**
 * PurchaseOrderCreate
 */
export type PurchaseOrderCreate = {
    amount_ugx: number;
    expected_date?: string | null;
    items?: Array<CommercialLineItemInput>;
    notes?: string | null;
    order_date: string;
    po_number: string;
    project_id?: string | null;
    status?: string;
    supplier_id?: string | null;
    supplier_name: string;
};

/**
 * PurchaseOrderRead
 */
export type PurchaseOrderRead = {
    amount_ugx: number;
    created_at: string;
    expected_date: string | null;
    id: string;
    items?: Array<CommercialLineItemRead>;
    notes: string | null;
    order_date: string;
    po_number: string;
    project_id: string | null;
    status: string;
    supplier_id: string | null;
    supplier_name: string;
    updated_at: string;
};

/**
 * PurchaseOrderUpdate
 */
export type PurchaseOrderUpdate = {
    amount_ugx?: number | null;
    expected_date?: string | null;
    items?: Array<CommercialLineItemInput>;
    notes?: string | null;
    order_date?: string | null;
    project_id?: string | null;
    status?: string | null;
    supplier_id?: string | null;
    supplier_name?: string | null;
};

/**
 * QuotationConvertRequest
 */
export type QuotationConvertRequest = {
    due_date?: string | null;
    issue_date: string;
    notes?: string | null;
};

/**
 * QuotationCreate
 */
export type QuotationCreate = {
    amount_ugx: number;
    client_id?: string | null;
    client_name: string;
    issue_date: string;
    items?: Array<CommercialLineItemInput>;
    notes?: string | null;
    project_id?: string | null;
    quotation_number: string;
    status?: string;
    valid_until?: string | null;
};

/**
 * QuotationRead
 */
export type QuotationRead = {
    amount_ugx: number;
    client_id: string | null;
    client_name: string;
    created_at: string;
    id: string;
    issue_date: string;
    items?: Array<CommercialLineItemRead>;
    notes: string | null;
    project_id: string | null;
    quotation_number: string;
    status: string;
    updated_at: string;
    valid_until: string | null;
};

/**
 * QuotationUpdate
 */
export type QuotationUpdate = {
    amount_ugx?: number | null;
    client_id?: string | null;
    client_name?: string | null;
    issue_date?: string | null;
    items?: Array<CommercialLineItemInput>;
    notes?: string | null;
    project_id?: string | null;
    status?: string | null;
    valid_until?: string | null;
};

/**
 * ReceiptRead
 */
export type ReceiptRead = {
    amount_ugx: number;
    client_id: string | null;
    client_name: string | null;
    created_at: string;
    id: string;
    invoice_id: string | null;
    invoice_number: string | null;
    method: string;
    notes: string | null;
    payment_date: string;
    project_id: string | null;
    receipt_reference: string;
    recorded_by_email: string;
    reference: string | null;
};

/**
 * StatementEntry
 */
export type StatementEntry = {
    credit_ugx: number;
    debit_ugx: number;
    entry_date: string;
    kind: string;
    record_id: string;
    reference: string;
    running_balance_ugx: number;
    status?: string | null;
};

/**
 * SupplierCreate
 */
export type SupplierCreate = {
    address?: string | null;
    contact_person?: string | null;
    email?: string | null;
    name: string;
    notes?: string | null;
    phone?: string | null;
};

/**
 * SupplierRead
 */
export type SupplierRead = {
    address: string | null;
    contact_person: string | null;
    created_at: string;
    email: string | null;
    id: string;
    is_active: boolean;
    name: string;
    notes: string | null;
    phone: string | null;
    updated_at: string;
};

/**
 * SupplierStatementSummary
 */
export type SupplierStatementSummary = {
    expenses_ugx: number;
    purchase_orders_ugx: number;
    supplier_id: string;
    supplier_name: string;
};

/**
 * SupplierUpdate
 */
export type SupplierUpdate = {
    address?: string | null;
    contact_person?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    name?: string | null;
    notes?: string | null;
    phone?: string | null;
};

/**
 * SupplierWorkspace
 */
export type SupplierWorkspace = {
    activity: Array<ActivityItem>;
    documents: Array<PartyDocumentItem>;
    expenses: Array<ExpenseRead>;
    expenses_total_ugx: number;
    projects: Array<PartyProjectItem>;
    purchase_orders: Array<PurchaseOrderRead>;
    purchase_orders_total_ugx: number;
    supplier: SupplierRead;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    assignee_email?: string | null;
    description?: string | null;
    due_date?: string | null;
    priority?: string;
    project_id: string;
    related_document_id?: string | null;
    start_date?: string | null;
    status?: string;
    title: string;
};

/**
 * TaskDashboardSummary
 */
export type TaskDashboardSummary = {
    assigned_to_me: number;
    due_today: number;
    high_priority: number;
    overdue: number;
    recently_completed: number;
};

/**
 * TaskRead
 */
export type TaskRead = {
    assignee_email: string | null;
    completed_at: string | null;
    created_at: string;
    description: string | null;
    due_date: string | null;
    id: string;
    priority: string;
    project_id: string;
    related_document_id: string | null;
    start_date: string | null;
    status: string;
    title: string;
    updated_at: string;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    assignee_email?: string | null;
    clear_due_date?: boolean;
    clear_related_document?: boolean;
    clear_start_date?: boolean;
    description?: string | null;
    due_date?: string | null;
    priority?: string | null;
    project_id?: string | null;
    related_document_id?: string | null;
    start_date?: string | null;
    status?: string | null;
    title?: string | null;
};

/**
 * TelemetryRecord
 */
export type TelemetryRecord = {
    current_a: number;
    frequency_hz: number;
    power_factor: number;
    timestamp_epoch: number;
    transformer_id: string;
    voltage_v: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    access_token: string;
    expires_in?: number;
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * UserAdminCreate
 */
export type UserAdminCreate = {
    email: string;
    full_name: string;
    is_active?: boolean;
    is_superuser?: boolean;
    password: string;
};

/**
 * UserAdminUpdate
 */
export type UserAdminUpdate = {
    email?: string | null;
    full_name?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    password?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    email: string;
    full_name: string;
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    email: string;
    full_name: string;
    id: string;
    is_active: boolean;
    is_superuser: boolean;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    email?: string | null;
    full_name?: string | null;
    password?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    count: number;
    data: Array<UserRead>;
};

/**
 * WorkspaceSummary
 */
export type WorkspaceSummary = {
    active_projects: number;
    documents: number;
    due_tasks: number;
    outstanding_ugx: number;
    pending_tasks: number;
};

export type ApiV1AuthLoginLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type ApiV1AuthLoginLoginResponses = {
    /**
     * Document created, URL follows
     */
    201: TokenResponse;
};

export type ApiV1AuthLoginLoginResponse = ApiV1AuthLoginLoginResponses[keyof ApiV1AuthLoginLoginResponses];

export type ApiV1AuthLogoutLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type ApiV1AuthLogoutLogoutResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type ApiV1AuthLogoutLogoutResponse = ApiV1AuthLogoutLogoutResponses[keyof ApiV1AuthLogoutLogoutResponses];

export type ApiV1AuthTokenTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token';
};

export type ApiV1AuthTokenTokenResponses = {
    /**
     * Document created, URL follows
     */
    201: TokenResponse;
};

export type ApiV1AuthTokenTokenResponse = ApiV1AuthTokenTokenResponses[keyof ApiV1AuthTokenTokenResponses];

export type ApiV1BusinessClientsClientsData = {
    body?: never;
    path?: never;
    query?: {
        include_inactive?: boolean;
    };
    url: '/api/v1/business/clients';
};

export type ApiV1BusinessClientsClientsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsClientsError = ApiV1BusinessClientsClientsErrors[keyof ApiV1BusinessClientsClientsErrors];

export type ApiV1BusinessClientsClientsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ClientRead>;
};

export type ApiV1BusinessClientsClientsResponse = ApiV1BusinessClientsClientsResponses[keyof ApiV1BusinessClientsClientsResponses];

export type ApiV1BusinessClientsCreateClientData = {
    body: ClientCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/clients';
};

export type ApiV1BusinessClientsCreateClientErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsCreateClientError = ApiV1BusinessClientsCreateClientErrors[keyof ApiV1BusinessClientsCreateClientErrors];

export type ApiV1BusinessClientsCreateClientResponses = {
    /**
     * Document created, URL follows
     */
    201: ClientRead;
};

export type ApiV1BusinessClientsCreateClientResponse = ApiV1BusinessClientsCreateClientResponses[keyof ApiV1BusinessClientsCreateClientResponses];

export type ApiV1BusinessClientsClientIdUpdateClientData = {
    body: ClientUpdate;
    path: {
        client_id: string;
    };
    query?: never;
    url: '/api/v1/business/clients/{client_id}';
};

export type ApiV1BusinessClientsClientIdUpdateClientErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsClientIdUpdateClientError = ApiV1BusinessClientsClientIdUpdateClientErrors[keyof ApiV1BusinessClientsClientIdUpdateClientErrors];

export type ApiV1BusinessClientsClientIdUpdateClientResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ClientRead;
};

export type ApiV1BusinessClientsClientIdUpdateClientResponse = ApiV1BusinessClientsClientIdUpdateClientResponses[keyof ApiV1BusinessClientsClientIdUpdateClientResponses];

export type ApiV1BusinessClientsClientIdStatementClientStatementData = {
    body?: never;
    path: {
        client_id: string;
    };
    query?: never;
    url: '/api/v1/business/clients/{client_id}/statement';
};

export type ApiV1BusinessClientsClientIdStatementClientStatementErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsClientIdStatementClientStatementError = ApiV1BusinessClientsClientIdStatementClientStatementErrors[keyof ApiV1BusinessClientsClientIdStatementClientStatementErrors];

export type ApiV1BusinessClientsClientIdStatementClientStatementResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<StatementEntry>;
};

export type ApiV1BusinessClientsClientIdStatementClientStatementResponse = ApiV1BusinessClientsClientIdStatementClientStatementResponses[keyof ApiV1BusinessClientsClientIdStatementClientStatementResponses];

export type ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentData = {
    body?: never;
    path: {
        client_id: string;
    };
    query?: never;
    url: '/api/v1/business/clients/{client_id}/statement/document';
};

export type ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentError = ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentErrors[keyof ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentErrors];

export type ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: CommercialDocumentRead;
};

export type ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentResponse = ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentResponses[keyof ApiV1BusinessClientsClientIdStatementDocumentGenerateClientStatementDocumentResponses];

export type ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadData = {
    body?: never;
    path: {
        client_id: string;
    };
    query?: never;
    url: '/api/v1/business/clients/{client_id}/statement/pdf';
};

export type ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadError = ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadErrors[keyof ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadErrors];

export type ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadResponse = ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadResponses[keyof ApiV1BusinessClientsClientIdStatementPdfClientStatementPdfDownloadResponses];

export type ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceData = {
    body?: never;
    path: {
        client_id: string;
    };
    query?: never;
    url: '/api/v1/business/clients/{client_id}/workspace';
};

export type ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceError = ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceErrors[keyof ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceErrors];

export type ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ClientWorkspace;
};

export type ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceResponse = ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceResponses[keyof ApiV1BusinessClientsClientIdWorkspaceClientWorkspaceResponses];

export type ApiV1BusinessExpensesExpensesData = {
    body?: never;
    path?: never;
    query?: {
        supplier_id?: string | null;
        project_id?: string | null;
    };
    url: '/api/v1/business/expenses';
};

export type ApiV1BusinessExpensesExpensesErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessExpensesExpensesError = ApiV1BusinessExpensesExpensesErrors[keyof ApiV1BusinessExpensesExpensesErrors];

export type ApiV1BusinessExpensesExpensesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ExpenseRead>;
};

export type ApiV1BusinessExpensesExpensesResponse = ApiV1BusinessExpensesExpensesResponses[keyof ApiV1BusinessExpensesExpensesResponses];

export type ApiV1BusinessExpensesCreateExpenseData = {
    body: ExpenseCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/expenses';
};

export type ApiV1BusinessExpensesCreateExpenseErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessExpensesCreateExpenseError = ApiV1BusinessExpensesCreateExpenseErrors[keyof ApiV1BusinessExpensesCreateExpenseErrors];

export type ApiV1BusinessExpensesCreateExpenseResponses = {
    /**
     * Document created, URL follows
     */
    201: ExpenseRead;
};

export type ApiV1BusinessExpensesCreateExpenseResponse = ApiV1BusinessExpensesCreateExpenseResponses[keyof ApiV1BusinessExpensesCreateExpenseResponses];

export type ApiV1BusinessInvoicesInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        client_id?: string | null;
        project_id?: string | null;
    };
    url: '/api/v1/business/invoices';
};

export type ApiV1BusinessInvoicesInvoicesErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessInvoicesInvoicesError = ApiV1BusinessInvoicesInvoicesErrors[keyof ApiV1BusinessInvoicesInvoicesErrors];

export type ApiV1BusinessInvoicesInvoicesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<InvoiceRead>;
};

export type ApiV1BusinessInvoicesInvoicesResponse = ApiV1BusinessInvoicesInvoicesResponses[keyof ApiV1BusinessInvoicesInvoicesResponses];

export type ApiV1BusinessInvoicesCreateInvoiceData = {
    body: InvoiceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/invoices';
};

export type ApiV1BusinessInvoicesCreateInvoiceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessInvoicesCreateInvoiceError = ApiV1BusinessInvoicesCreateInvoiceErrors[keyof ApiV1BusinessInvoicesCreateInvoiceErrors];

export type ApiV1BusinessInvoicesCreateInvoiceResponses = {
    /**
     * Document created, URL follows
     */
    201: InvoiceRead;
};

export type ApiV1BusinessInvoicesCreateInvoiceResponse = ApiV1BusinessInvoicesCreateInvoiceResponses[keyof ApiV1BusinessInvoicesCreateInvoiceResponses];

export type ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceData = {
    body: InvoiceUpdate;
    path: {
        invoice_id: string;
    };
    query?: never;
    url: '/api/v1/business/invoices/{invoice_id}';
};

export type ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceError = ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceErrors[keyof ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceErrors];

export type ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: InvoiceRead;
};

export type ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceResponse = ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceResponses[keyof ApiV1BusinessInvoicesInvoiceIdUpdateInvoiceResponses];

export type ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentData = {
    body?: never;
    path: {
        invoice_id: string;
    };
    query?: never;
    url: '/api/v1/business/invoices/{invoice_id}/document';
};

export type ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentError = ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentErrors[keyof ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentErrors];

export type ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: CommercialDocumentRead;
};

export type ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentResponse = ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentResponses[keyof ApiV1BusinessInvoicesInvoiceIdDocumentGenerateInvoiceDocumentResponses];

export type ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadData = {
    body?: never;
    path: {
        invoice_id: string;
    };
    query?: never;
    url: '/api/v1/business/invoices/{invoice_id}/pdf';
};

export type ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadError = ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadErrors[keyof ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadErrors];

export type ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadResponse = ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadResponses[keyof ApiV1BusinessInvoicesInvoiceIdPdfInvoicePdfDownloadResponses];

export type ApiV1BusinessPaymentsPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        client_id?: string | null;
        project_id?: string | null;
        invoice_id?: string | null;
    };
    url: '/api/v1/business/payments';
};

export type ApiV1BusinessPaymentsPaymentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPaymentsPaymentsError = ApiV1BusinessPaymentsPaymentsErrors[keyof ApiV1BusinessPaymentsPaymentsErrors];

export type ApiV1BusinessPaymentsPaymentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PaymentRead>;
};

export type ApiV1BusinessPaymentsPaymentsResponse = ApiV1BusinessPaymentsPaymentsResponses[keyof ApiV1BusinessPaymentsPaymentsResponses];

export type ApiV1BusinessPaymentsCreatePaymentData = {
    body: PaymentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/payments';
};

export type ApiV1BusinessPaymentsCreatePaymentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPaymentsCreatePaymentError = ApiV1BusinessPaymentsCreatePaymentErrors[keyof ApiV1BusinessPaymentsCreatePaymentErrors];

export type ApiV1BusinessPaymentsCreatePaymentResponses = {
    /**
     * Document created, URL follows
     */
    201: PaymentRead;
};

export type ApiV1BusinessPaymentsCreatePaymentResponse = ApiV1BusinessPaymentsCreatePaymentResponses[keyof ApiV1BusinessPaymentsCreatePaymentResponses];

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersData = {
    body?: never;
    path?: never;
    query?: {
        supplier_id?: string | null;
        project_id?: string | null;
    };
    url: '/api/v1/business/purchase-orders';
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersError = ApiV1BusinessPurchaseOrdersPurchaseOrdersErrors[keyof ApiV1BusinessPurchaseOrdersPurchaseOrdersErrors];

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<PurchaseOrderRead>;
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrdersResponse = ApiV1BusinessPurchaseOrdersPurchaseOrdersResponses[keyof ApiV1BusinessPurchaseOrdersPurchaseOrdersResponses];

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderData = {
    body: PurchaseOrderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/purchase-orders';
};

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderError = ApiV1BusinessPurchaseOrdersCreatePurchaseOrderErrors[keyof ApiV1BusinessPurchaseOrdersCreatePurchaseOrderErrors];

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponses = {
    /**
     * Document created, URL follows
     */
    201: PurchaseOrderRead;
};

export type ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponse = ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponses[keyof ApiV1BusinessPurchaseOrdersCreatePurchaseOrderResponses];

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderData = {
    body: PurchaseOrderUpdate;
    path: {
        purchase_order_id: string;
    };
    query?: never;
    url: '/api/v1/business/purchase-orders/{purchase_order_id}';
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderError = ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderErrors[keyof ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderErrors];

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PurchaseOrderRead;
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderResponse = ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderResponses[keyof ApiV1BusinessPurchaseOrdersPurchaseOrderIdUpdatePurchaseOrderResponses];

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentData = {
    body?: never;
    path: {
        purchase_order_id: string;
    };
    query?: never;
    url: '/api/v1/business/purchase-orders/{purchase_order_id}/document';
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentError = ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentErrors[keyof ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentErrors];

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: CommercialDocumentRead;
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentResponse = ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentResponses[keyof ApiV1BusinessPurchaseOrdersPurchaseOrderIdDocumentGeneratePurchaseOrderDocumentResponses];

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadData = {
    body?: never;
    path: {
        purchase_order_id: string;
    };
    query?: never;
    url: '/api/v1/business/purchase-orders/{purchase_order_id}/pdf';
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadError = ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadErrors[keyof ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadErrors];

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadResponse = ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadResponses[keyof ApiV1BusinessPurchaseOrdersPurchaseOrderIdPdfPurchaseOrderPdfDownloadResponses];

export type ApiV1BusinessQuotationsQuotationsData = {
    body?: never;
    path?: never;
    query?: {
        client_id?: string | null;
        project_id?: string | null;
    };
    url: '/api/v1/business/quotations';
};

export type ApiV1BusinessQuotationsQuotationsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsQuotationsError = ApiV1BusinessQuotationsQuotationsErrors[keyof ApiV1BusinessQuotationsQuotationsErrors];

export type ApiV1BusinessQuotationsQuotationsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<QuotationRead>;
};

export type ApiV1BusinessQuotationsQuotationsResponse = ApiV1BusinessQuotationsQuotationsResponses[keyof ApiV1BusinessQuotationsQuotationsResponses];

export type ApiV1BusinessQuotationsCreateQuotationData = {
    body: QuotationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/quotations';
};

export type ApiV1BusinessQuotationsCreateQuotationErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsCreateQuotationError = ApiV1BusinessQuotationsCreateQuotationErrors[keyof ApiV1BusinessQuotationsCreateQuotationErrors];

export type ApiV1BusinessQuotationsCreateQuotationResponses = {
    /**
     * Document created, URL follows
     */
    201: QuotationRead;
};

export type ApiV1BusinessQuotationsCreateQuotationResponse = ApiV1BusinessQuotationsCreateQuotationResponses[keyof ApiV1BusinessQuotationsCreateQuotationResponses];

export type ApiV1BusinessQuotationsQuotationIdUpdateQuotationData = {
    body: QuotationUpdate;
    path: {
        quotation_id: string;
    };
    query?: never;
    url: '/api/v1/business/quotations/{quotation_id}';
};

export type ApiV1BusinessQuotationsQuotationIdUpdateQuotationErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsQuotationIdUpdateQuotationError = ApiV1BusinessQuotationsQuotationIdUpdateQuotationErrors[keyof ApiV1BusinessQuotationsQuotationIdUpdateQuotationErrors];

export type ApiV1BusinessQuotationsQuotationIdUpdateQuotationResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: QuotationRead;
};

export type ApiV1BusinessQuotationsQuotationIdUpdateQuotationResponse = ApiV1BusinessQuotationsQuotationIdUpdateQuotationResponses[keyof ApiV1BusinessQuotationsQuotationIdUpdateQuotationResponses];

export type ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceData = {
    body: QuotationConvertRequest;
    path: {
        quotation_id: string;
    };
    query?: never;
    url: '/api/v1/business/quotations/{quotation_id}/convert-to-invoice';
};

export type ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceError = ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceErrors[keyof ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceErrors];

export type ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceResponses = {
    /**
     * Document created, URL follows
     */
    201: InvoiceRead;
};

export type ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceResponse = ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceResponses[keyof ApiV1BusinessQuotationsQuotationIdConvertToInvoiceConvertQuotationToInvoiceResponses];

export type ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentData = {
    body?: never;
    path: {
        quotation_id: string;
    };
    query?: never;
    url: '/api/v1/business/quotations/{quotation_id}/document';
};

export type ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentError = ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentErrors[keyof ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentErrors];

export type ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: CommercialDocumentRead;
};

export type ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentResponse = ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentResponses[keyof ApiV1BusinessQuotationsQuotationIdDocumentGenerateQuotationDocumentResponses];

export type ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadData = {
    body?: never;
    path: {
        quotation_id: string;
    };
    query?: never;
    url: '/api/v1/business/quotations/{quotation_id}/pdf';
};

export type ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadError = ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadErrors[keyof ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadErrors];

export type ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadResponse = ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadResponses[keyof ApiV1BusinessQuotationsQuotationIdPdfQuotationPdfDownloadResponses];

export type ApiV1BusinessReceiptsReceiptsData = {
    body?: never;
    path?: never;
    query?: {
        client_id?: string | null;
        project_id?: string | null;
    };
    url: '/api/v1/business/receipts';
};

export type ApiV1BusinessReceiptsReceiptsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessReceiptsReceiptsError = ApiV1BusinessReceiptsReceiptsErrors[keyof ApiV1BusinessReceiptsReceiptsErrors];

export type ApiV1BusinessReceiptsReceiptsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ReceiptRead>;
};

export type ApiV1BusinessReceiptsReceiptsResponse = ApiV1BusinessReceiptsReceiptsResponses[keyof ApiV1BusinessReceiptsReceiptsResponses];

export type ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentData = {
    body?: never;
    path: {
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/business/receipts/{payment_id}/document';
};

export type ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentError = ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentErrors[keyof ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentErrors];

export type ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: CommercialDocumentRead;
};

export type ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentResponse = ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentResponses[keyof ApiV1BusinessReceiptsPaymentIdDocumentGenerateReceiptDocumentResponses];

export type ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadData = {
    body?: never;
    path: {
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/business/receipts/{payment_id}/pdf';
};

export type ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadError = ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadErrors[keyof ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadErrors];

export type ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadResponse = ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadResponses[keyof ApiV1BusinessReceiptsPaymentIdPdfReceiptPdfDownloadResponses];

export type ApiV1BusinessStatementsClientsClientStatementSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/statements/clients';
};

export type ApiV1BusinessStatementsClientsClientStatementSummariesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ClientStatementSummary>;
};

export type ApiV1BusinessStatementsClientsClientStatementSummariesResponse = ApiV1BusinessStatementsClientsClientStatementSummariesResponses[keyof ApiV1BusinessStatementsClientsClientStatementSummariesResponses];

export type ApiV1BusinessStatementsSuppliersSupplierStatementSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/statements/suppliers';
};

export type ApiV1BusinessStatementsSuppliersSupplierStatementSummariesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<SupplierStatementSummary>;
};

export type ApiV1BusinessStatementsSuppliersSupplierStatementSummariesResponse = ApiV1BusinessStatementsSuppliersSupplierStatementSummariesResponses[keyof ApiV1BusinessStatementsSuppliersSupplierStatementSummariesResponses];

export type ApiV1BusinessSummarySummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/business/summary';
};

export type ApiV1BusinessSummarySummaryResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: BusinessSummary;
};

export type ApiV1BusinessSummarySummaryResponse = ApiV1BusinessSummarySummaryResponses[keyof ApiV1BusinessSummarySummaryResponses];

export type ApiV1BusinessSuppliersSuppliersData = {
    body?: never;
    path?: never;
    query?: {
        include_inactive?: boolean;
    };
    url: '/api/v1/business/suppliers';
};

export type ApiV1BusinessSuppliersSuppliersErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersSuppliersError = ApiV1BusinessSuppliersSuppliersErrors[keyof ApiV1BusinessSuppliersSuppliersErrors];

export type ApiV1BusinessSuppliersSuppliersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<SupplierRead>;
};

export type ApiV1BusinessSuppliersSuppliersResponse = ApiV1BusinessSuppliersSuppliersResponses[keyof ApiV1BusinessSuppliersSuppliersResponses];

export type ApiV1BusinessSuppliersCreateSupplierData = {
    body: SupplierCreate;
    path?: never;
    query?: never;
    url: '/api/v1/business/suppliers';
};

export type ApiV1BusinessSuppliersCreateSupplierErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersCreateSupplierError = ApiV1BusinessSuppliersCreateSupplierErrors[keyof ApiV1BusinessSuppliersCreateSupplierErrors];

export type ApiV1BusinessSuppliersCreateSupplierResponses = {
    /**
     * Document created, URL follows
     */
    201: SupplierRead;
};

export type ApiV1BusinessSuppliersCreateSupplierResponse = ApiV1BusinessSuppliersCreateSupplierResponses[keyof ApiV1BusinessSuppliersCreateSupplierResponses];

export type ApiV1BusinessSuppliersSupplierIdUpdateSupplierData = {
    body: SupplierUpdate;
    path: {
        supplier_id: string;
    };
    query?: never;
    url: '/api/v1/business/suppliers/{supplier_id}';
};

export type ApiV1BusinessSuppliersSupplierIdUpdateSupplierErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersSupplierIdUpdateSupplierError = ApiV1BusinessSuppliersSupplierIdUpdateSupplierErrors[keyof ApiV1BusinessSuppliersSupplierIdUpdateSupplierErrors];

export type ApiV1BusinessSuppliersSupplierIdUpdateSupplierResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SupplierRead;
};

export type ApiV1BusinessSuppliersSupplierIdUpdateSupplierResponse = ApiV1BusinessSuppliersSupplierIdUpdateSupplierResponses[keyof ApiV1BusinessSuppliersSupplierIdUpdateSupplierResponses];

export type ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentData = {
    body?: never;
    path: {
        supplier_id: string;
    };
    query?: never;
    url: '/api/v1/business/suppliers/{supplier_id}/statement/document';
};

export type ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentError = ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentErrors[keyof ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentErrors];

export type ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: CommercialDocumentRead;
};

export type ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentResponse = ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentResponses[keyof ApiV1BusinessSuppliersSupplierIdStatementDocumentGenerateSupplierStatementDocumentResponses];

export type ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadData = {
    body?: never;
    path: {
        supplier_id: string;
    };
    query?: never;
    url: '/api/v1/business/suppliers/{supplier_id}/statement/pdf';
};

export type ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadError = ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadErrors[keyof ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadErrors];

export type ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadResponse = ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadResponses[keyof ApiV1BusinessSuppliersSupplierIdStatementPdfSupplierStatementPdfDownloadResponses];

export type ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceData = {
    body?: never;
    path: {
        supplier_id: string;
    };
    query?: never;
    url: '/api/v1/business/suppliers/{supplier_id}/workspace';
};

export type ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceError = ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceErrors[keyof ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceErrors];

export type ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SupplierWorkspace;
};

export type ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceResponse = ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceResponses[keyof ApiV1BusinessSuppliersSupplierIdWorkspaceSupplierWorkspaceResponses];

export type ApiV1DocumentsListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        project_id?: string | null;
        client_id?: string | null;
        supplier_id?: string | null;
        q?: string | null;
    };
    url: '/api/v1/documents';
};

export type ApiV1DocumentsListDocumentsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsListDocumentsError = ApiV1DocumentsListDocumentsErrors[keyof ApiV1DocumentsListDocumentsErrors];

export type ApiV1DocumentsListDocumentsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<DocumentRead>;
};

export type ApiV1DocumentsListDocumentsResponse = ApiV1DocumentsListDocumentsResponses[keyof ApiV1DocumentsListDocumentsResponses];

export type ApiV1DocumentsCreateDocumentData = {
    body: DocumentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/documents';
};

export type ApiV1DocumentsCreateDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsCreateDocumentError = ApiV1DocumentsCreateDocumentErrors[keyof ApiV1DocumentsCreateDocumentErrors];

export type ApiV1DocumentsCreateDocumentResponses = {
    /**
     * Document created, URL follows
     */
    201: DocumentRead;
};

export type ApiV1DocumentsCreateDocumentResponse = ApiV1DocumentsCreateDocumentResponses[keyof ApiV1DocumentsCreateDocumentResponses];

export type ApiV1DocumentsPresignCreateUploadUrlData = {
    body: DocumentPresignRequest;
    path?: never;
    query?: never;
    url: '/api/v1/documents/presign';
};

export type ApiV1DocumentsPresignCreateUploadUrlErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsPresignCreateUploadUrlError = ApiV1DocumentsPresignCreateUploadUrlErrors[keyof ApiV1DocumentsPresignCreateUploadUrlErrors];

export type ApiV1DocumentsPresignCreateUploadUrlResponses = {
    /**
     * Document created, URL follows
     */
    201: DocumentPresignResponse;
};

export type ApiV1DocumentsPresignCreateUploadUrlResponse = ApiV1DocumentsPresignCreateUploadUrlResponses[keyof ApiV1DocumentsPresignCreateUploadUrlResponses];

export type ApiV1DocumentsDocumentIdDeleteDocumentData = {
    body?: never;
    path: {
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type ApiV1DocumentsDocumentIdDeleteDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsDocumentIdDeleteDocumentError = ApiV1DocumentsDocumentIdDeleteDocumentErrors[keyof ApiV1DocumentsDocumentIdDeleteDocumentErrors];

export type ApiV1DocumentsDocumentIdDeleteDocumentResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiV1DocumentsDocumentIdDeleteDocumentResponse = ApiV1DocumentsDocumentIdDeleteDocumentResponses[keyof ApiV1DocumentsDocumentIdDeleteDocumentResponses];

export type ApiV1DocumentsDocumentIdUpdateDocumentData = {
    body: DocumentUpdate;
    path: {
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type ApiV1DocumentsDocumentIdUpdateDocumentErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsDocumentIdUpdateDocumentError = ApiV1DocumentsDocumentIdUpdateDocumentErrors[keyof ApiV1DocumentsDocumentIdUpdateDocumentErrors];

export type ApiV1DocumentsDocumentIdUpdateDocumentResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DocumentRead;
};

export type ApiV1DocumentsDocumentIdUpdateDocumentResponse = ApiV1DocumentsDocumentIdUpdateDocumentResponses[keyof ApiV1DocumentsDocumentIdUpdateDocumentResponses];

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlData = {
    body?: never;
    path: {
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/download';
};

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlError = ApiV1DocumentsDocumentIdDownloadGetDownloadUrlErrors[keyof ApiV1DocumentsDocumentIdDownloadGetDownloadUrlErrors];

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DownloadResponse;
};

export type ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponse = ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponses[keyof ApiV1DocumentsDocumentIdDownloadGetDownloadUrlResponses];

export type ApiV1ProjectsListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string | null;
        include_archived?: boolean;
        status?: string | null;
        client?: string | null;
        manager?: string | null;
        start_from?: string | null;
        start_to?: string | null;
        deadline_from?: string | null;
        deadline_to?: string | null;
        progress_min?: number | null;
        progress_max?: number | null;
        value_min?: number | null;
        value_max?: number | null;
        tag?: string | null;
    };
    url: '/api/v1/projects';
};

export type ApiV1ProjectsListProjectsErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsListProjectsError = ApiV1ProjectsListProjectsErrors[keyof ApiV1ProjectsListProjectsErrors];

export type ApiV1ProjectsListProjectsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<ProjectRead>;
};

export type ApiV1ProjectsListProjectsResponse = ApiV1ProjectsListProjectsResponses[keyof ApiV1ProjectsListProjectsResponses];

export type ApiV1ProjectsCreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type ApiV1ProjectsCreateProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsCreateProjectError = ApiV1ProjectsCreateProjectErrors[keyof ApiV1ProjectsCreateProjectErrors];

export type ApiV1ProjectsCreateProjectResponses = {
    /**
     * Document created, URL follows
     */
    201: ProjectRead;
};

export type ApiV1ProjectsCreateProjectResponse = ApiV1ProjectsCreateProjectResponses[keyof ApiV1ProjectsCreateProjectResponses];

export type ApiV1ProjectsDashboardDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects/dashboard';
};

export type ApiV1ProjectsDashboardDashboardResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectDashboardSummary;
};

export type ApiV1ProjectsDashboardDashboardResponse = ApiV1ProjectsDashboardDashboardResponses[keyof ApiV1ProjectsDashboardDashboardResponses];

export type ApiV1ProjectsProjectIdArchiveProjectData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ApiV1ProjectsProjectIdArchiveProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdArchiveProjectError = ApiV1ProjectsProjectIdArchiveProjectErrors[keyof ApiV1ProjectsProjectIdArchiveProjectErrors];

export type ApiV1ProjectsProjectIdArchiveProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiV1ProjectsProjectIdArchiveProjectResponse = ApiV1ProjectsProjectIdArchiveProjectResponses[keyof ApiV1ProjectsProjectIdArchiveProjectResponses];

export type ApiV1ProjectsProjectIdGetProjectData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ApiV1ProjectsProjectIdGetProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdGetProjectError = ApiV1ProjectsProjectIdGetProjectErrors[keyof ApiV1ProjectsProjectIdGetProjectErrors];

export type ApiV1ProjectsProjectIdGetProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectRead;
};

export type ApiV1ProjectsProjectIdGetProjectResponse = ApiV1ProjectsProjectIdGetProjectResponses[keyof ApiV1ProjectsProjectIdGetProjectResponses];

export type ApiV1ProjectsProjectIdUpdateProjectData = {
    body: ProjectUpdate;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ApiV1ProjectsProjectIdUpdateProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdUpdateProjectError = ApiV1ProjectsProjectIdUpdateProjectErrors[keyof ApiV1ProjectsProjectIdUpdateProjectErrors];

export type ApiV1ProjectsProjectIdUpdateProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectRead;
};

export type ApiV1ProjectsProjectIdUpdateProjectResponse = ApiV1ProjectsProjectIdUpdateProjectResponses[keyof ApiV1ProjectsProjectIdUpdateProjectResponses];

export type ApiV1ProjectsProjectIdDuplicateDuplicateProjectData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/duplicate';
};

export type ApiV1ProjectsProjectIdDuplicateDuplicateProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdDuplicateDuplicateProjectError = ApiV1ProjectsProjectIdDuplicateDuplicateProjectErrors[keyof ApiV1ProjectsProjectIdDuplicateDuplicateProjectErrors];

export type ApiV1ProjectsProjectIdDuplicateDuplicateProjectResponses = {
    /**
     * Document created, URL follows
     */
    201: ProjectRead;
};

export type ApiV1ProjectsProjectIdDuplicateDuplicateProjectResponse = ApiV1ProjectsProjectIdDuplicateDuplicateProjectResponses[keyof ApiV1ProjectsProjectIdDuplicateDuplicateProjectResponses];

export type ApiV1ProjectsProjectIdRestoreRestoreProjectData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/restore';
};

export type ApiV1ProjectsProjectIdRestoreRestoreProjectErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdRestoreRestoreProjectError = ApiV1ProjectsProjectIdRestoreRestoreProjectErrors[keyof ApiV1ProjectsProjectIdRestoreRestoreProjectErrors];

export type ApiV1ProjectsProjectIdRestoreRestoreProjectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectRead;
};

export type ApiV1ProjectsProjectIdRestoreRestoreProjectResponse = ApiV1ProjectsProjectIdRestoreRestoreProjectResponses[keyof ApiV1ProjectsProjectIdRestoreRestoreProjectResponses];

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceData = {
    body?: never;
    path: {
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/workspace';
};

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceError = ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceErrors[keyof ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceErrors];

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProjectWorkspaceRead;
};

export type ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponse = ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponses[keyof ApiV1ProjectsProjectIdWorkspaceGetProjectWorkspaceResponses];

export type ApiV1TasksListTasksData = {
    body?: never;
    path?: never;
    query?: {
        project_id?: string | null;
        status?: string | null;
        priority?: string | null;
        assignee?: string | null;
        mine?: boolean;
        q?: string | null;
        start_from?: string | null;
        start_to?: string | null;
        due_from?: string | null;
        due_to?: string | null;
        include_archived_projects?: boolean;
    };
    url: '/api/v1/tasks';
};

export type ApiV1TasksListTasksErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksListTasksError = ApiV1TasksListTasksErrors[keyof ApiV1TasksListTasksErrors];

export type ApiV1TasksListTasksResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<TaskRead>;
};

export type ApiV1TasksListTasksResponse = ApiV1TasksListTasksResponses[keyof ApiV1TasksListTasksResponses];

export type ApiV1TasksCreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tasks';
};

export type ApiV1TasksCreateTaskErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksCreateTaskError = ApiV1TasksCreateTaskErrors[keyof ApiV1TasksCreateTaskErrors];

export type ApiV1TasksCreateTaskResponses = {
    /**
     * Document created, URL follows
     */
    201: TaskRead;
};

export type ApiV1TasksCreateTaskResponse = ApiV1TasksCreateTaskResponses[keyof ApiV1TasksCreateTaskResponses];

export type ApiV1TasksDashboardDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/dashboard';
};

export type ApiV1TasksDashboardDashboardResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TaskDashboardSummary;
};

export type ApiV1TasksDashboardDashboardResponse = ApiV1TasksDashboardDashboardResponses[keyof ApiV1TasksDashboardDashboardResponses];

export type ApiV1TasksTaskIdDeleteTaskData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type ApiV1TasksTaskIdDeleteTaskErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksTaskIdDeleteTaskError = ApiV1TasksTaskIdDeleteTaskErrors[keyof ApiV1TasksTaskIdDeleteTaskErrors];

export type ApiV1TasksTaskIdDeleteTaskResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiV1TasksTaskIdDeleteTaskResponse = ApiV1TasksTaskIdDeleteTaskResponses[keyof ApiV1TasksTaskIdDeleteTaskResponses];

export type ApiV1TasksTaskIdUpdateTaskData = {
    body: TaskUpdate;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type ApiV1TasksTaskIdUpdateTaskErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TasksTaskIdUpdateTaskError = ApiV1TasksTaskIdUpdateTaskErrors[keyof ApiV1TasksTaskIdUpdateTaskErrors];

export type ApiV1TasksTaskIdUpdateTaskResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TaskRead;
};

export type ApiV1TasksTaskIdUpdateTaskResponse = ApiV1TasksTaskIdUpdateTaskResponses[keyof ApiV1TasksTaskIdUpdateTaskResponses];

export type ApiV1TelemetryIngestIngestData = {
    body: Array<TelemetryRecord>;
    path?: never;
    query?: never;
    url: '/api/v1/telemetry/ingest';
};

export type ApiV1TelemetryIngestIngestErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1TelemetryIngestIngestError = ApiV1TelemetryIngestIngestErrors[keyof ApiV1TelemetryIngestIngestErrors];

export type ApiV1TelemetryIngestIngestResponses = {
    /**
     * Request accepted, processing continues off-line
     */
    202: {
        [key: string]: unknown;
    };
};

export type ApiV1TelemetryIngestIngestResponse = ApiV1TelemetryIngestIngestResponses[keyof ApiV1TelemetryIngestIngestResponses];

export type ApiV1UsersListUsersData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/users';
};

export type ApiV1UsersListUsersErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersListUsersError = ApiV1UsersListUsersErrors[keyof ApiV1UsersListUsersErrors];

export type ApiV1UsersListUsersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UsersPublic;
};

export type ApiV1UsersListUsersResponse = ApiV1UsersListUsersResponses[keyof ApiV1UsersListUsersResponses];

export type ApiV1UsersCreateUserAdminData = {
    body: UserAdminCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type ApiV1UsersCreateUserAdminErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersCreateUserAdminError = ApiV1UsersCreateUserAdminErrors[keyof ApiV1UsersCreateUserAdminErrors];

export type ApiV1UsersCreateUserAdminResponses = {
    /**
     * Document created, URL follows
     */
    201: UserRead;
};

export type ApiV1UsersCreateUserAdminResponse = ApiV1UsersCreateUserAdminResponses[keyof ApiV1UsersCreateUserAdminResponses];

export type ApiV1UsersMeDeleteMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ApiV1UsersMeDeleteMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type ApiV1UsersMeDeleteMeResponse = ApiV1UsersMeDeleteMeResponses[keyof ApiV1UsersMeDeleteMeResponses];

export type ApiV1UsersMeGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ApiV1UsersMeGetMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersMeGetMeResponse = ApiV1UsersMeGetMeResponses[keyof ApiV1UsersMeGetMeResponses];

export type ApiV1UsersMeUpdateMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ApiV1UsersMeUpdateMeErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersMeUpdateMeError = ApiV1UsersMeUpdateMeErrors[keyof ApiV1UsersMeUpdateMeErrors];

export type ApiV1UsersMeUpdateMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersMeUpdateMeResponse = ApiV1UsersMeUpdateMeResponses[keyof ApiV1UsersMeUpdateMeResponses];

export type ApiV1UsersMePasswordUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type ApiV1UsersMePasswordUpdatePasswordMeErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersMePasswordUpdatePasswordMeError = ApiV1UsersMePasswordUpdatePasswordMeErrors[keyof ApiV1UsersMePasswordUpdatePasswordMeErrors];

export type ApiV1UsersMePasswordUpdatePasswordMeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type ApiV1UsersMePasswordUpdatePasswordMeResponse = ApiV1UsersMePasswordUpdatePasswordMeResponses[keyof ApiV1UsersMePasswordUpdatePasswordMeResponses];

export type ApiV1UsersRegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/register';
};

export type ApiV1UsersRegisterRegisterErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersRegisterRegisterError = ApiV1UsersRegisterRegisterErrors[keyof ApiV1UsersRegisterRegisterErrors];

export type ApiV1UsersRegisterRegisterResponses = {
    /**
     * Document created, URL follows
     */
    201: UserRead;
};

export type ApiV1UsersRegisterRegisterResponse = ApiV1UsersRegisterRegisterResponses[keyof ApiV1UsersRegisterRegisterResponses];

export type ApiV1UsersSignupSignupData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type ApiV1UsersSignupSignupErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersSignupSignupError = ApiV1UsersSignupSignupErrors[keyof ApiV1UsersSignupSignupErrors];

export type ApiV1UsersSignupSignupResponses = {
    /**
     * Document created, URL follows
     */
    201: UserRead;
};

export type ApiV1UsersSignupSignupResponse = ApiV1UsersSignupSignupResponses[keyof ApiV1UsersSignupSignupResponses];

export type ApiV1UsersUserIdDeleteUserData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ApiV1UsersUserIdDeleteUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdDeleteUserError = ApiV1UsersUserIdDeleteUserErrors[keyof ApiV1UsersUserIdDeleteUserErrors];

export type ApiV1UsersUserIdDeleteUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type ApiV1UsersUserIdDeleteUserResponse = ApiV1UsersUserIdDeleteUserResponses[keyof ApiV1UsersUserIdDeleteUserResponses];

export type ApiV1UsersUserIdGetUserByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ApiV1UsersUserIdGetUserByIdErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdGetUserByIdError = ApiV1UsersUserIdGetUserByIdErrors[keyof ApiV1UsersUserIdGetUserByIdErrors];

export type ApiV1UsersUserIdGetUserByIdResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersUserIdGetUserByIdResponse = ApiV1UsersUserIdGetUserByIdResponses[keyof ApiV1UsersUserIdGetUserByIdResponses];

export type ApiV1UsersUserIdUpdateUserAdminData = {
    body: UserAdminUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ApiV1UsersUserIdUpdateUserAdminErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdUpdateUserAdminError = ApiV1UsersUserIdUpdateUserAdminErrors[keyof ApiV1UsersUserIdUpdateUserAdminErrors];

export type ApiV1UsersUserIdUpdateUserAdminResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersUserIdUpdateUserAdminResponse = ApiV1UsersUserIdUpdateUserAdminResponses[keyof ApiV1UsersUserIdUpdateUserAdminResponses];

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminData = {
    body: UserAdminUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/role';
};

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminError = ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors[keyof ApiV1UsersUserIdRoleUpdateUserRoleAdminErrors];

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: UserRead;
};

export type ApiV1UsersUserIdRoleUpdateUserRoleAdminResponse = ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses[keyof ApiV1UsersUserIdRoleUpdateUserRoleAdminResponses];

export type ApiV1UtilsHealthCheckHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check';
};

export type ApiV1UtilsHealthCheckHealthCheckResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: boolean;
};

export type ApiV1UtilsHealthCheckHealthCheckResponse = ApiV1UtilsHealthCheckHealthCheckResponses[keyof ApiV1UtilsHealthCheckHealthCheckResponses];

export type ApiV1UtilsTestEmailTestEmailData = {
    body: {
        [key: string]: unknown;
    } | null;
    path?: never;
    query?: {
        email_to?: string | null;
    };
    url: '/api/v1/utils/test-email';
};

export type ApiV1UtilsTestEmailTestEmailErrors = {
    /**
     * Validation Exception
     */
    400: {
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
        status_code: number;
    };
};

export type ApiV1UtilsTestEmailTestEmailError = ApiV1UtilsTestEmailTestEmailErrors[keyof ApiV1UtilsTestEmailTestEmailErrors];

export type ApiV1UtilsTestEmailTestEmailResponses = {
    /**
     * Document created, URL follows
     */
    201: Message;
};

export type ApiV1UtilsTestEmailTestEmailResponse = ApiV1UtilsTestEmailTestEmailResponses[keyof ApiV1UtilsTestEmailTestEmailResponses];

export type ApiV1WorkspaceSummarySummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workspace/summary';
};

export type ApiV1WorkspaceSummarySummaryResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: WorkspaceSummary;
};

export type ApiV1WorkspaceSummarySummaryResponse = ApiV1WorkspaceSummarySummaryResponses[keyof ApiV1WorkspaceSummarySummaryResponses];

export type HealthGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthGetHealthResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type HealthGetHealthResponse = HealthGetHealthResponses[keyof HealthGetHealthResponses];

export type HealthLiveGetLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveGetLivenessResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type HealthLiveGetLivenessResponse = HealthLiveGetLivenessResponses[keyof HealthLiveGetLivenessResponses];

export type HealthReadyGetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyGetReadinessResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthReadyGetReadinessResponse = HealthReadyGetReadinessResponses[keyof HealthReadyGetReadinessResponses];

export type HealthStartupGetStartupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/startup';
};

export type HealthStartupGetStartupResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthStartupGetStartupResponse = HealthStartupGetStartupResponses[keyof HealthStartupGetStartupResponses];

export type MetricsMetricsEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type MetricsMetricsEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: string;
};

export type MetricsMetricsEndpointResponse = MetricsMetricsEndpointResponses[keyof MetricsMetricsEndpointResponses];
